#
# fetch-upstream..yml
#
# Copyright (c) Microsoft Corporation. All rights reserved.
#
# Github action to push the latest upstream changes to our repo.
#

# Every day at midnight, run this.
name: Fetch Upstream
on:
  schedule:
  - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Refresh-Upstream:
    name: update_upstream_branches
    env:
      upstream_project_name: "lustre-release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set repo URL
        run: echo "git://git.whamcloud.com/fs/$upstream_project_name.git" >> $GITHUB_ENV
      - run: |
          echo "Fetching branches and tags from $lustre_upstream_url"
          cd $upstream_project_name
          git remote add upstream $lustre_upstream_url
          git fetch upstream
          git fetch --tags upstream
        name: "Fetch the latest changes and tags from upstream"

      - run: |
          git push origin --tags
          for b in $(ls .git/refs/remotes/upstream); do
            echo "Pushing updates to branch $b"
            git push -f origin upstream/${b}:refs/heads/upstream/${b};
          done
        name: "Push tags and changes from the upstream branches"
